# -*- coding: utf-8 -*-
"""Inference1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1brYegRjUcHZrqglblW3khXiQUKcDcjvZ
"""

import os
import matplotlib.pyplot as plt
import matplotlib.image as mpimg
import numpy as np
import pandas as pd

loc=os.getcwd()
from keras.models import load_model
model = load_model(loc+'/saved_model.h5')

an=os.listdir(loc+'/sample_images')
img=[]
for i in range(len(an)):
    img.append(mpimg.imread(loc+'/sample_images/'+an[i]))

data_img=np.ndarray((len(img),224,224,3))
count=len(img)
for i in range(len(img)):
    data_img[i]=img[i]

dic={0: 'apple', 1: 'banana', 2: 'bread', 3: 'bruscitt', 4: 'cake', 5: 'carrot', 6: 'cutlet', 7: 'fennel_gratin', 8: 'fillet_fish', 9: 'fries', 10: 'green_beans', 11: 'lasagna_bolognese', 12: 'meat', 13: 'orange', 14: 'pasta', 15: 'pears', 16: 'peas', 17: 'pizza', 18: 'pizzoccheri', 19: 'potatoes', 20: 'pudding', 21: 'rice', 22: 'salad', 23: 'salmon', 24: 'salty_cake', 25: 'savory_pie', 26: 'scallops', 27: 'soup', 28: 'spinach', 29: 'squid_stew', 30: 'tangerine', 31: 'wet_zucchini', 32: 'yogurt'}

preds=model.predict(data_img)
preds[preds>=0.5] = 1
preds[preds<0.5] = 0

b=[]
for i in range(len(preds)):
    a=[]
    for j,e in enumerate(preds[i]):
        if preds[i][j]==1:
            a.append(j)
    b.append(a)

c=[]
for i in range(len(b)):
    d=[]
    for j in range(len(b[i])):
        d.append(dic[b[i][j]])
    c.append(d)

out = pd.DataFrame(an, columns=['image'])
out['label']=c

out.to_csv('output.csv')

print('csv file created')
